// flow-typed signature: e758a8fb6cda0f34fb346c231b1d9e3d
// flow-typed version: <<STUB>>/fixpack_v2.3.1/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fixpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fixpack' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fixpack/fixpack' {
  declare module.exports: any
}

// Filename aliases
declare module 'fixpack/fixpack.js' {
  declare module.exports: $Exports<'fixpack/fixpack'>
}
